[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","SIM","RUF"]
ignore = ["E501"]
fix = true

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_ignores = true
