services:
  - type: web
    name: valhalla-api
    runtime: docker
    plan: starter
    region: oregon
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///./heimdall.db
