DEAL_DECISION_RULES = {
    "prime_rule": "Heimdall must protect capital before chasing profit.",
    "wholesale_rules": {
        "minimum_assignment_spread": 10000,
        "preferred_assignment_spread": 20000,
        "strong_assignment_spread": 30000,
        "max_offer_formula": "(arv * 0.70) - repairs - assignment_fee - safety_buffer",
        "required_checks": [
            "seller motivation",
            "clear title path",
            "buyer demand",
            "repair estimate",
            "ARV confidence",
            "legal review required before contract",
        ],
    },
    "brrrr_rules": {
        "minimum_cashflow_after_refi": 200,
        "preferred_cashflow_after_refi": 400,
        "minimum_equity_after_refi_percent": 15,
        "required_checks": [
            "rental demand",
            "vacancy rate",
            "repair budget",
            "refinance likelihood",
            "lender criteria",
            "property management options",
        ],
    },
    "flip_rules": {
        "minimum_profit": 25000,
        "preferred_profit": 50000,
        "minimum_roi_percent": 15,
        "required_checks": [
            "accurate ARV",
            "contractor availability",
            "permit risk",
            "holding cost",
            "market days",
            "exit buyer demand",
        ],
    },
    "automatic_reject_flags": [
        "unknown title risk",
        "seller cannot prove authority",
        "repair estimate unavailable",
        "no buyer demand",
        "negative cashflow with no strategic reason",
        "legal uncertainty unresolved",
        "numbers only work under best-case assumptions",
    ],
    "heimdall_output_required": [
        "deal_score",
        "buy_pass_recommendation",
        "risk_summary",
        "missing_information",
        "next_best_action",
        "human_approval_required",
    ],
}
