"""
PACK CI4: Insight Synthesizer Models
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, JSON
from app.models.base import Base


class Insight(Base):
    """
    High-level insight generated by Heimdall or the system.

    Example:
    - "You are over-committed in Q1 relative to your energy levels."
    - "This contractor has declining reliability."
    """
    __tablename__ = "insights"

    id = Column(Integer, primary_key=True, index=True)
    source = Column(String, nullable=False)         # "heimdall", "system", "manual"
    category = Column(String, nullable=False)       # "finance", "security", "family", "system", etc.
    title = Column(String, nullable=False)
    body = Column(Text, nullable=False)
    importance = Column(Integer, nullable=False, default=5)  # 1–10
    tags = Column(JSON, nullable=True)
    context = Column(JSON, nullable=True)          # optional detailed context
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
