"""Deterministic SQLAlchemy model registry.

This module exists only to import canonical model modules so their declarative
classes are registered on ``app.core.db.Base.metadata``.

Constraints for this module:
- Import-only; no DB operations.
- No FastAPI, routers, services, or startup hooks.
- No wildcard scanning or dynamic filesystem discovery.
"""

import app.accounting.models  # noqa: F401
import app.advanced_negotiation.models  # noqa: F401
import app.arbitrage.models  # noqa: F401
import app.audit.models  # noqa: F401
import app.behavior.models  # noqa: F401
import app.behavioral_profiling.models  # noqa: F401
import app.blackice.models  # noqa: F401
import app.brrrr.models  # noqa: F401
import app.children.models  # noqa: F401
import app.closers.models  # noqa: F401
import app.compliance.models  # noqa: F401
import app.deal_analyzer.models  # noqa: F401
import app.docs.models  # noqa: F401
import app.finops.models  # noqa: F401
import app.freeze.models  # noqa: F401
import app.god.models  # noqa: F401
import app.influence.models  # noqa: F401
import app.integrity.models  # noqa: F401
import app.king.models  # noqa: F401
import app.knowledge.models  # noqa: F401
import app.leads.models  # noqa: F401
import app.legal.models  # noqa: F401
import app.loki.models  # noqa: F401
import app.messaging.models  # noqa: F401
import app.models.api_clients  # noqa: F401
import app.models.audit_event  # noqa: F401
import app.models.audit_log  # noqa: F401
import app.models.banking_structure_planner  # noqa: F401
import app.models.brain_state  # noqa: F401
import app.models.brrrr_planner  # noqa: F401
import app.models.builder  # noqa: F401
import app.models.buyer_candidate  # noqa: F401
import app.models.buyer_liquidity  # noqa: F401
import app.models.capital  # noqa: F401
import app.models.children  # noqa: F401
import app.models.community  # noqa: F401
import app.models.contract_record  # noqa: F401
import app.models.contracts  # noqa: F401
import app.models.cra_organization  # noqa: F401
import app.models.credit_card_spending  # noqa: F401
import app.models.daily_rhythm  # noqa: F401
import app.models.data_lineage  # noqa: F401
import app.models.data_retention  # noqa: F401
import app.models.deal  # noqa: F401
import app.models.deal_buyer_match  # noqa: F401
import app.models.deal_notification  # noqa: F401
import app.models.decision_governance  # noqa: F401
import app.models.decision_outcome  # noqa: F401
import app.models.decision_recommendation  # noqa: F401
import app.models.dispo  # noqa: F401
import app.models.disputes  # noqa: F401
import app.models.document_route  # noqa: F401
import app.models.education_engine  # noqa: F401
import app.models.empire_governance  # noqa: F401
import app.models.empire_journal  # noqa: F401
import app.models.engine_readiness  # noqa: F401
import app.models.engine_state  # noqa: F401
import app.models.entity_links  # noqa: F401
import app.models.event_log  # noqa: F401
import app.models.execution_case  # noqa: F401
import app.models.execution_event  # noqa: F401
import app.models.execution_policy  # noqa: F401
import app.models.explanation_logs  # noqa: F401
import app.models.export_job  # noqa: F401
import app.models.feature_flags  # noqa: F401
import app.models.followup_task  # noqa: F401
import app.models.freeze_events  # noqa: F401
import app.models.go_live_state  # noqa: F401
import app.models.god_case  # noqa: F401
import app.models.god_verdicts  # noqa: F401
import app.models.governance_decision  # noqa: F401
import app.models.grant_eligibility  # noqa: F401
import app.models.grants  # noqa: F401
import app.models.heimdall_event  # noqa: F401
import app.models.heimdall_policy  # noqa: F401
import app.models.heimdall_recommendation  # noqa: F401
import app.models.heimdall_scorecard  # noqa: F401
import app.models.heimdall_workload  # noqa: F401
import app.models.holdings  # noqa: F401
import app.models.honeypot_bridge  # noqa: F401
import app.models.income_engine  # noqa: F401
import app.models.income_routing  # noqa: F401
import app.models.insight  # noqa: F401
import app.models.intake  # noqa: F401
import app.models.investor_module  # noqa: F401
import app.models.kids_education  # noqa: F401
import app.models.kpi_event  # noqa: F401
import app.models.lead_intake  # noqa: F401
import app.models.lead_source  # noqa: F401
import app.models.legal_profile  # noqa: F401
import app.models.maintenance  # noqa: F401
import app.models.market_policy  # noqa: F401
import app.models.match  # noqa: F401
import app.models.media_engine  # noqa: F401
import app.models.meeting_recordings  # noqa: F401
import app.models.mental_load  # noqa: F401
import app.models.model_provider  # noqa: F401
import app.models.narrative  # noqa: F401
import app.models.normalized_lead  # noqa: F401
import app.models.notification_bridge  # noqa: F401
import app.models.notification_channel  # noqa: F401
import app.models.notification_orchestrator  # noqa: F401
import app.models.notify  # noqa: F401
import app.models.offer_evidence  # noqa: F401
import app.models.offer_policy  # noqa: F401
import app.models.opportunity  # noqa: F401
import app.models.pack_so_legacy  # noqa: F401
import app.models.pack_sp  # noqa: F401
import app.models.pack_sq  # noqa: F401
import app.models.pack_st  # noqa: F401
import app.models.pack_su  # noqa: F401
import app.models.pack_sv  # noqa: F401
import app.models.pending_action  # noqa: F401
import app.models.personal_dashboard  # noqa: F401
import app.models.philosophy  # noqa: F401
import app.models.pro_retainer  # noqa: F401
import app.models.pro_scorecard  # noqa: F401
import app.models.pro_task_link  # noqa: F401
import app.models.projection_framework  # noqa: F401
import app.models.rate_limit  # noqa: F401
import app.models.raw_lead  # noqa: F401
import app.models.registration_navigator  # noqa: F401
import app.models.regression_policy  # noqa: F401
import app.models.regression_state  # noqa: F401
import app.models.relationships  # noqa: F401
import app.models.research  # noqa: F401
import app.models.revenue_ledger  # noqa: F401
import app.models.risk_event  # noqa: F401
import app.models.risk_ledger  # noqa: F401
import app.models.risk_policy  # noqa: F401
import app.models.saas_access  # noqa: F401
import app.models.sandbox_event  # noqa: F401
import app.models.sandbox_human_label  # noqa: F401
import app.models.scenario_simulator  # noqa: F401
import app.models.scheduled_job  # noqa: F401
import app.models.security_actions  # noqa: F401
import app.models.security_policy  # noqa: F401
import app.models.specialist_feedback  # noqa: F401
import app.models.story_engine  # noqa: F401
import app.models.story_mode  # noqa: F401
import app.models.strategic_decision  # noqa: F401
import app.models.strategic_event  # noqa: F401
import app.models.strategic_mode  # noqa: F401
import app.models.system_check_job  # noqa: F401
import app.models.system_config  # noqa: F401
import app.models.system_log  # noqa: F401
import app.models.system_metadata  # noqa: F401
import app.models.task  # noqa: F401
import app.models.tax_interpretations  # noqa: F401
import app.models.telemetry_event  # noqa: F401
import app.models.training_job  # noqa: F401
import app.models.trajectory  # noqa: F401
import app.models.trajectory_target  # noqa: F401
import app.models.triggers  # noqa: F401
import app.models.trust_residency  # noqa: F401
import app.models.tuning_rules  # noqa: F401
import app.models.underwriter_assessment  # noqa: F401
import app.models.user_summary  # noqa: F401
import app.models.va_approval_queue  # noqa: F401
import app.models.va_audit_log  # noqa: F401
import app.models.va_lead  # noqa: F401
import app.models.vehicle_tracking  # noqa: F401
import app.models.wholesale  # noqa: F401
import app.models.wholesale_deals  # noqa: F401
import app.models.workflow_guardrails  # noqa: F401
import app.neg_enhance.models  # noqa: F401
import app.negotiation_strategies.models  # noqa: F401
import app.negotiations.models  # noqa: F401
import app.offers.models  # noqa: F401
import app.orchestrator.models  # noqa: F401
import app.pantry.models  # noqa: F401
import app.payments.models  # noqa: F401
import app.policies.models  # noqa: F401
import app.providers.models  # noqa: F401
import app.queen.models  # noqa: F401
import app.rbac.models  # noqa: F401
import app.resort.models  # noqa: F401
import app.specialists.models  # noqa: F401
import app.sync.models  # noqa: F401
import app.users.models  # noqa: F401
import app.workflows.models  # noqa: F401
