"""pack_56_legacy_systems

Revision ID: fdc9b660a48f
Revises: 61eede990fb0
Create Date: 2025-11-20 10:35:28.017342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc9b660a48f'
down_revision: Union[str, Sequence[str], None] = '61eede990fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_name', sa.String(length=100), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ACTIVE', 'SCALING', 'PAUSED', 'ARCHIVED', name='legacy_status_enum'), nullable=False),
    sa.Column('cloned_from', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('clone_count', sa.Integer(), nullable=False),
    sa.Column('last_clone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_systems_code_name'), 'legacy_systems', ['code_name'], unique=False)
    op.create_index(op.f('ix_legacy_systems_id'), 'legacy_systems', ['id'], unique=False)
    op.create_index(op.f('ix_legacy_systems_status'), 'legacy_systems', ['status'], unique=False)
    op.create_index(op.f('ix_legacy_systems_template_key'), 'legacy_systems', ['template_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legacy_systems_template_key'), table_name='legacy_systems')
    op.drop_index(op.f('ix_legacy_systems_status'), table_name='legacy_systems')
    op.drop_index(op.f('ix_legacy_systems_id'), table_name='legacy_systems')
    op.drop_index(op.f('ix_legacy_systems_code_name'), table_name='legacy_systems')
    op.drop_table('legacy_systems')
    # ### end Alembic commands ###
