version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  web:
    image: node:20
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    volumes:
      - ./frontend:/app
    environment:
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
    ports:
      - "3000:3000"
    depends_on:
      - api

  worker:
    build: ./backend
    env_file: .env
    depends_on:
      - redis
      - db
    command: python -u worker.py

  minio:
    image: minio/minio:RELEASE.2025-01-11T07-00-00Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio_data:/data

  mc:
    image: minio/mc:RELEASE.2025-01-11T07-00-00Z
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
        mc alias set local ${S3_ENDPOINT_URL} ${S3_ACCESS_KEY} ${S3_SECRET_KEY} --api s3v4 &&
        mc mb -p local/${S3_BUCKET} || true &&
        mc anonymous set public local/${S3_BUCKET}/public || true &&
        sleep 3600
      "
    environment:
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}

volumes:
  db_data:
  minio_data:
