HEIMDALL_ERROR_CATCHER_RULES = {
    "prime_rule": "Protect capital first. Never approve a deal that only works under best-case assumptions.",
    "automatic_reject": [
        "seller cannot prove authority",
        "title issue unresolved",
        "no clear exit buyer",
        "repair estimate missing",
        "ARV unsupported by comparable sales",
        "negative cashflow with no strategic reason",
        "legal review required but skipped",
        "numbers only work if everything goes perfectly",
        "contract terms unclear",
        "deal depends on unrealistic rent",
        "deal depends on unrealistic refinance",
        "contractor quote unavailable for major repairs",
    ],
    "human_approval_required": [
        "first deal in any new market",
        "assignment contract",
        "seller-facing legal document",
        "private lending/JV agreement",
        "cross-border deal",
        "deal involving trusts/entities",
        "renovation over approved threshold",
        "any tax strategy",
        "any insurance/infinite banking action",
        "any arbitrage leverage increase",
    ],
    "deal_score_weights": {
        "seller_motivation": 20,
        "spread_margin": 20,
        "arv_confidence": 15,
        "repair_confidence": 15,
        "buyer_demand": 15,
        "legal_clarity": 10,
        "market_strength": 5,
    },
    "recommendation_bands": {
        "85_100": "strong_candidate_but_still_requires_human_approval",
        "70_84": "possible_candidate_needs_more_due_diligence",
        "50_69": "weak_candidate_high_caution",
        "0_49": "reject_or_hold",
    },
}
