apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: prometheus
        tags: ["trace_id"]
        mappedTags:
          - key: "trace_id"
            value: "trace_id"
      nodeGraph:
        enabled: true
